1.14.1077

diff --git a/vivaldi-source/chromium/third_party/libvpx/source/libvpx/configure b/vivaldi-source/chromium/third_party/libvpx/source/libvpx/configure
--- a/vivaldi-source/chromium/third_party/libvpx/source/libvpx/configure
+++ b/vivaldi-source/chromium/third_party/libvpx/source/libvpx/configure
@@ -170,10 +170,13 @@ for t in ${all_targets}; do
     [ -f "${source_path}/${t}.mk" ] && enable_feature ${t}
 done
 
+if ! diff --version >/dev/null; then
+  die "diff missing: Try installing diffutils via your package manager."
+fi
+
 if ! perl --version >/dev/null; then
     die "Perl is required to build"
 fi
-
 
 if [ "`cd \"${source_path}\" && pwd`" != "`pwd`" ]; then
   # test to see if source_path already configured
@@ -241,6 +244,7 @@ ARCH_EXT_LIST_X86="
     sse4_1
     avx
     avx2
+    avx512
 "
 
 ARCH_EXT_LIST_LOONGSON="
